In [11]:
import numpy as np

# Caminho para o arquivo salvo pela função `save_network_as_npz`
npz_filename = "../src/rede.npz"

# Carrega o arquivo
data = np.load(npz_filename)

# Acessa o array salvo com a chave "network"
network = data["network"]

print("Shape da rede:", network.shape)
print("Rede (exemplo):\n", network)

Shape da rede: (100, 10000)
Rede (exemplo):
 [[0 1 1 ... 0 0 1]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
import numpy as np

# Caminho para o arquivo salvo pela função `save_p_values_as_npy`
npy_filename = "../src/p.npy"

# Carrega diretamente o vetor p(t)
p = np.load(npy_filename)

print("Tamanho de p:", len(p))
print("p(t):", p)


Tamanho de p: 100
p(t): [0.8 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
